CUDA_VISIBLE_DEVICES=0,1,2 torchrun --nproc_per_node=3 --master_port=20001 judgelm/train/train.py \
    --model_name_or_path="Llama-2-7b-chat-hf" \
    --data_path judgelm/data/judgelm_train_100k.jsonl \
    --bf16 True \
    --output_dir="alpaca/output/judgelm-debug-evaluator" \
    --num_train_epochs 2 \
    --per_device_train_batch_size 3 \
    --per_device_eval_batch_size 3 \
    --gradient_accumulation_steps 32 \
    --evaluation_strategy no \
    --save_strategy steps \
    --save_steps 1200 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap "LlamaDecoderLayer" \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --disable_tqdm False \
    --run_name 7B-full-model